// app/layout.tsx (or pages/_app.tsx if using Pages Router)
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/mobile/Navbar";
import { UserProvider } from "../context/UserContext"; // Import the UserProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider> {/* Wrap children with UserProvider */}
          {children}
          <Navbar />
        </UserProvider>
      </body>
    </html>
  );
}
