// app/layout.tsx (or pages/_app.tsx if using Pages Router)
import type { Metadata } from "next";

import "./globals.css";
import Navbar from "../components/mobile/Navbar";
import { UserProvider } from "../context/UserContext";
import Header from "@/components/desktop/Header";
import { CartProvider } from "@/context/CartContext";
import { DateProvider } from "@/context/DateContext";

export const metadata: Metadata = {
  title: "Nordic Experiences",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <CartProvider>
            <DateProvider>
              <Header />
              <div className="sm:mt-24">{children}</div>
              <Navbar />
            </DateProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
